### ISSUE TITLE
Не хватает 2х исключений Exception в конструкторе для отрицательных значений полей класса CreditAccount

### ISSUE THREAD

**Issue by cistercii91** [pachimar1/javaqateamwork#3]
# Описание
В конструкторе класса CreditAccount  требуется добавить 2 исключения IllegalArgumentException для полей balance  и creditLimit, и проверки их на отрицательные числа, т.к. по условиям задачи значения всех полей должны быть положительными.

# Локация дефекта
https://github.com/pachimar1/javaqateamwork/blob/79dde7c39bcdfc2d7132d39b826bf5a283a1cb86/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L24-L28

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/pachimar1/javaqateamwork/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA (класс CreditAccountTest).
2. Найти тесты checkInitialBalanceForNegativeValue и попытаться создать объект класса CreditAccount с параметрами: initialBalance = -5_000, creditLimit = 5_000, rate = 15.
3. Найти тесты checkCreditLimitForNegativeValue и попытаться создать объект класса CreditAccount с параметрами: initialBalance = 5_000, creditLimit = -5_000, rate = 15.

**_Ожидаемый результат:_**
При создании объекта должно выбрасываться исключение `IllegalArgumentException` с соответствующим сообщением о некорректных параметрах.

**_Фактический результат:_**
`IllegalArgumentException` не выбрасывается, и объект создается без ошибок.

# Скриншот
![image](https://user-images.githubusercontent.com/103969442/235526332-02435085-607a-4593-ba4c-57171a3490d6.png)

# Окружение
* **Операционная система:** Windows 11 21H2
*  **IDE:** IntelliJ IDEA 2022.3.2 (Community version)
*  **Java:** OpenJDK 11

**Comment by pachimar1** [comment]
баг исправлен, тесты проходят
