### ISSUE TITLE
Метод  "public boolean pay ( )" класса CreditAccoun не выполняет требования задачи при его вызове.

### ISSUE THREAD

**Issue by cistercii91** [pachimar1/javaqateamwork#4]
# Описание
В методе "public boolean pay ( )" неправильно описана логика вычисления нового баланса при выполнении покупки. Если ничего не исправлять, то нарушатся следующие требвания:
1. "... Если же операция может привести к некорректному
    состоянию счёта (например, баланс может уйти в минус), то операция должна
    завершиться вернув false и ничего не поменяв на счёте..."

на строке 48 ([код](https://github.com/pachimar1/javaqateamwork/blob/79dde7c39bcdfc2d7132d39b826bf5a283a1cb86/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L44-L55)) выполняется вычитание из balance, а значит в независимости от конечного результата (true или false) баланс уже изменен.

2. "...В результате успешного вызова этого метода, баланс должен уменьшиться
    на сумму покупки ..."

На строке 50 ([код](https://github.com/pachimar1/javaqateamwork/blob/79dde7c39bcdfc2d7132d39b826bf5a283a1cb86/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L44-L55)) поле balance принимает значение переменной "-amount" (знак минуса "-" стоит после равенства "=").

# Локация дефекта
https://github.com/pachimar1/javaqateamwork/blob/79dde7c39bcdfc2d7132d39b826bf5a283a1cb86/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L44-L55

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/pachimar1/javaqateamwork/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA (класс CreditAccountTest).
2. Найти тест balanceChangedAfterPurchase передать значения initialBalance: 1_000, creditBalance: 5_000, rate: 15
        boolean actual = false;
        account.pay(100);
        if (account.getBalance() == 900) {
            actual = true;
        }

**_Ожидаемый результат:_**
true

**_Фактический результат:_**
false

# Скриншот
![image](https://user-images.githubusercontent.com/103969442/236349909-71c56206-f292-4b78-b76b-51767a2c33e3.png)

# Окружение
* **Операционная система:** Windows 11 21H2
*  **IDE:** IntelliJ IDEA 2022.3.2 (Community version)
*  **Java:** OpenJDK 11

# Рекомендую следующий код
    public boolean pay(int amount) {
        if (amount <= 0) {   
            return false;
        }
        temporaryBalance = balance - amount; 
        if (temporaryBalance  > -creditLimit) { 
            balance -= amount; 
            return true;
        } else {
            return false;  
        }
    }

**Comment by pachimar1** [comment]
баг исправлен, тесты проходят
