### ISSUE TITLE
Метод balance в классе CreditAccount не рассчитывается вновь при пополнении счета, присваивается значение add

### ISSUE THREAD

**Issue by cistercii91** [pachimar1/javaqateamwork#5]
# Описание
balance не рассчитывается вновь при пополнении счета, т.к. на строке 73  ([код](https://github.com/pachimar1/javaqateamwork/blob/79dde7c39bcdfc2d7132d39b826bf5a283a1cb86/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L73)) не выполняется действие сложения из-за отсутствия знака "+" (плюс) перед знаком "=" (равно).

# Локация дефекта
https://github.com/pachimar1/javaqateamwork/blob/b67d4a0f9ace73bb3c22d652e42c06076fc0aa97/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L69-L75

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/pachimar1/javaqateamwork/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA (класс CreditAccountTest).
2. Найти тест shouldAddToPositiveBalance передать значения initialBalance: 1, creditBalance: 5_000, rate: 15
3. Вызвать метод account.add с заданной суммой: 3_000

**_Ожидаемый результат:_**
3001

**_Фактический результат:_**
3000

# Скриншот
![image](https://user-images.githubusercontent.com/103969442/236346084-45fa9486-c070-4f98-a546-fe01bf90ef19.png)

# Окружение
* **Операционная система:** Windows 11 21H2
*  **IDE:** IntelliJ IDEA 2022.3.2 (Community version)
*  **Java:** OpenJDK 11

# Рекомендуемый код
balance += amount;

**Comment by pachimar1** [comment]
баг исправлен, тесты проходят
