### ISSUE TITLE
Нет проверки баланса на отрицательное значение в методе yearChange класса CreditAccount

### ISSUE THREAD

**Issue by cistercii91** [pachimar1/javaqateamwork#6]
# Описание
В методе yearChange класса CreditAccount  по условию задачи должна быть проверка баланса на отрицательное значение, однако в коде такой проверки нет и сразу выполняется определение процентной ставки. 
([код](https://github.com/pachimar1/javaqateamwork/blob/79dde7c39bcdfc2d7132d39b826bf5a283a1cb86/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L85-L88))

# Локация дефекта
https://github.com/pachimar1/javaqateamwork/blob/b67d4a0f9ace73bb3c22d652e42c06076fc0aa97/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L85-L88

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/pachimar1/javaqateamwork/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA (класс CreditAccountTest).
2. Найти тест BalanceValuesPositive и передать значения: initialBalance: 200, creditBalance: 5_000, rate: 15
3. Вызвать account.yearChange .

**_Ожидаемый результат:_**
0

**_Фактический результат:_**
30

# Скриншот
![image](https://user-images.githubusercontent.com/103969442/236351307-1063dbd1-5919-4276-b099-babd79170ae1.png)

# Окружение
* **Операционная система:** Windows 11 21H2
*  **IDE:** IntelliJ IDEA 2022.3.2 (Community version)
*  **Java:** OpenJDK 11

**Comment by pachimar1** [comment]
баг исправлен, тесты проходят
